In [1]:
import numpy as np

### Principios básicos

Craer arreglos

In [2]:
np.array([10, 20, 24, 5, 15, 50, 18])

array([10, 20, 24,  5, 15, 50, 18])

In [9]:
a = np.array([10, 30, 50, 43, 7, 2, 4, 40, 100])

Viualización de los arreglos

In [8]:
a[4]

7

In [5]:
a[3:]

array([ 43,   7,   2,   4,  40, 100])

In [6]:
a[3:6]

array([43,  7,  2])

In [7]:
a[3::3]

array([43,  4])

Crear arreglos de manera dinámica

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [20]:
b = np.array( [['x','y','z'], ['a','b','c']])
b

array([['x', 'y', 'z'],
       ['a', 'b', 'c']], dtype='<U1')

In [21]:
# numero de dimensiones
b.ndim

2

Ordenamiento

In [23]:
c = [12,4,3,6,4,7,8,5,90,5]
np.sort(c)

array([ 3,  4,  4,  5,  5,  6,  7,  8, 12, 90])

In [24]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype=cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

Creamos arreglos de manera dinámica

In [25]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
np.arange(3,25)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [27]:
np.arange(3,25,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [28]:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [29]:
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [30]:
cabeceras = [('nombre', 'S10'), ('edad', int), ('pais', 'S2')]
datos = [('Juan', 10, 'MX'), ('Maria', 70, 'CO'), ('Javier', 42, 'AR'), ('Samuel', 15, 'MX')]
usuarios = np.array(datos, dtype=cabeceras)

np.sort(usuarios, order = 'pais')

array([(b'Javier', 42, b'AR'), (b'Maria', 70, b'CO'),
       (b'Juan', 10, b'MX'), (b'Samuel', 15, b'MX')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S2')])

In [37]:
for a in np.sort(usuarios, order = 'pais'): 
    print(a) 

(b'Javier', 42, b'AR')
(b'Maria', 70, b'CO')
(b'Juan', 10, b'MX')
(b'Samuel', 15, b'MX')
