In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [2,4,5]])

In [3]:
U, D, V = np.linalg.svd(A)

In [4]:
print(U)

[[-0.48634367  0.87376761]
 [-0.87376761 -0.48634367]]


In [5]:
print(D)

[7.67561933 0.29132085]


In [6]:
print(np.diag(D))

[[7.67561933 0.        ]
 [0.         0.29132085]]


In [7]:
print(V)

[[-2.91035653e-01 -5.82071307e-01 -7.59270204e-01]
 [-3.39555958e-01 -6.79111916e-01  6.50775505e-01]
 [-8.94427191e-01  4.47213595e-01 -1.23214615e-15]]
