In [2]:
import numpy as np

In [3]:
A = np.array([[1,2,3,4,5,6], [2,4,5,7,8,9]])

In [4]:
U, D, V = np.linalg.svd(A)

In [5]:
print(U)

[[-0.52457485  0.85136433]
 [-0.85136433 -0.52457485]]


In [6]:
print(D)

[18.15420642  0.65175857]


In [7]:
print(np.diag(D))

[[18.15420642  0.        ]
 [ 0.          0.65175857]]


In [8]:
print(V)

[[-0.12268801 -0.24537603 -0.32116778 -0.4438558  -0.51964755 -0.59543931]
 [-0.30346418 -0.60692836 -0.10553184 -0.40899602  0.09240049  0.59379701]
 [-0.31678627 -0.09588435  0.90900846 -0.12747886 -0.14549577 -0.16351268]
 [-0.43966805 -0.39986805 -0.13239936  0.7690016  -0.16619968 -0.10140096]
 [-0.51069076  0.11221501 -0.14057527 -0.15143818  0.72971236 -0.38913709]
 [-0.58171346  0.62429808 -0.14875118 -0.07187796 -0.37437559  0.32312678]]
